name: fluid_side_menu
description: A premium, highly-customizable fluid side navigation menu with organic liquid-reveal transitions, staggered option entrance animations, and rich select feedback behaviors.
version: 1.2.0
homepage: https://github.com/GalaxyPhoenix716/fluid_side_menu_package
repository: https://github.com/GalaxyPhoenix716/fluid_side_menu_package
issue_tracker: https://github.com/GalaxyPhoenix716/fluid_side_menu_package/issues

environment:
  sdk: ^3.12.1
  flutter: ">=3.11.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
